### ISSUE TITLE
Python 3.5 Support?

### ISSUE THREAD

**Issue by shaunc869** [mattgwwalker/msg-extractor#10]
What needs to be done to update this to Python 3.5 support? Thanks for the great library!

**Comment by mattgwwalker** [comment]
Hey Shaun, it's been a fair while since I've looked at this program.  However there have been a number of people who've contributed fixes for different versions of Python.  If you're keen, by all means look into what's required for 3.5.  I'd more than happily accept your contribution!

Cheers,

Matthew

**Comment by Sicos1977** [comment]
Hi,

I have written an MSGReader... it is in .NET but you could try this to use it.

http://stackoverflow.com/questions/7367976/calling-a-c-sharp-library-from-python

You can find the MSGReader overhere --> https://github.com/Sicos1977/MSGReader

**Comment by pmlandwehr** [comment]
@shaunc869 Is it breaking for you on `py35`?

**Comment by meli-lewis** [comment]
I've also successfully built it using 3.5, but would also be interested in updating it. I also came here to say thanks, @mattgwwalker! This was enormously useful.
