### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by shree14** [mattgwwalker/msg-extractor#19]
Hi! I am new to python. I installed this library using pip and executed it as per the readme file. I did not get any output. The script executes without any error. Am I doing something wrong? Please help me with this.

**Comment by mattgwwalker** [comment]
If you provide details of what commands you ran and the directory structure of the files you're trying to process, I might be able to help.

**Comment by shree14** [comment]
I cloned this repository using git clone, then executed pip install -r requirements.txt, and then executed python ExtractMsg.py  abc.msg

**Comment by mattgwwalker** [comment]
And do you have a file called abc.msg in the directory from which you
called ExtractMsg.py?

**Comment by shree14** [comment]
Yes.

**Comment by shree14** [comment]
I figured out the actual issue. It's working fine now. The output was getting stored on location other than my pwd. Thank you for you help!

**Comment by shree14** [comment]
I need one more help. Can you please tell me if we can automate email extraction from outlook? As soon as I receive an email, my script should auto download it in a local folder

**Comment by mattgwwalker** [comment]
I can’t help you there. Sorry. If you have any luck, you might like to
share your technique should others be interested.

**Comment by shree14** [comment]
Sure! I will share if I find anything.

**Comment by yingchenwy** [comment]
can you tell me where was your output stored? thanks so  @shree14

**Comment by TheElementalOfCreation** [comment]
Output is stored in the calling directory. The script does not care about where the msg file is, just where you are.

**Comment by jj-06** [comment]
I'm not seeing any output in the calling directory. No error messages
Am I missing something?

**Comment by TheElementalOfCreation** [comment]
@jj-06 can you please send an example of an msg file that this happens with to arceusthe@gmail.com? Make sure to place it in a zip file before sending as some email clients will mess up the msg file otherwise.

By sending me an example I can confirm better if it is a problem with the code, the msg file, your system in particular, or a user error. Thank you.

**Comment by jj-06** [comment]
Thanks, Matt. I retried that with the Unicode.msg in the example-msg-file folder. Same observation.

Cheers,
June

On 21 Dec 2018, at 6:32 PM, Ken Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


@jj-06<https://github.com/jj-06> can you please send an example of an msg file that this happens with to arceusthe@gmail.com<mailto:arceusthe@gmail.com>? Make sure to place it in a zip file before sending as some email clients will mess up the msg file otherwise.

By sending me an example I can confirm better if it is a problem with the code, the msg file, your system in particular, or a user error. Thank you.

**Comment by TheElementalOfCreation** [comment]
@jj-06 Lol, this is Ken. Are you running it through the command line or are you importing it? 

If you are running it from the command line, can you try inserting the following lines of code into __main__.py immediately after the line ```if __name__ == '__main__':```:

```
    import os
    print(os.getcwd())
```
Once done, the code should look like:
```
...
if __name__ == '__main__':
    import os
    print(os.getcwd())
    if len(sys.argv) <= 1:
        print(__doc__)
...
```
After you have done that, run the code again and check inside of the directory printed for a new folder.

**Comment by jj-06** [comment]
Ken,
Basically the code prints out some system values into a text file. For now, I’m just calling the extract_msg within this code to figure out the format of the output from msg-extractor.

import extract_msg
msg = extract_msg.Message("Unicode.msg")

Cheers,
June

On 22 Dec 2018, at 10:26 PM, Ken Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


@jj-06<https://github.com/jj-06> No worries, we've all been there at some point. What exactly is the code that you are running?

**Comment by TheElementalOfCreation** [comment]
@jj-06 the reason you are not getting any output is because no function has been called to create output. The default function for generating output files would be `Message.save`. You have only initialized the class, which is basically just an interface between the user/user's code and the message file. While you can make the class save in a different way (something I do in my own programs), you are likely just going to want to call the save function of simply call it from the command line. The command line version is going to be getting a massive upgrade soon (version 0.21.0) and will be much more user friendly.

**Comment by jj-06** [comment]
Perfect, that worked! Silly me, thank you so much for pointing it out.

Cheers,
June

On 22 Dec 2018, at 10:46 PM, Ken Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


@jj-06<https://github.com/jj-06> the reason you are not getting any output is because no function has been called to create output. The default function for generating output files would be Message.save. You have only initialized the class, which is basically just an interface between the user/user's code and the message file. While you can make the class save in a different way (something I do in my own programs), you are likely just going to want to call the save function of simply call it from the command line. The command line version is going to be getting a massive upgrade soon (version 0.21.0) and will be much more user friendly.

**Comment by TheElementalOfCreation** [comment]
This issue should be completely solved. If for whatever reason it is not, Please comment and I might reopen it.
