### ISSUE TITLE
UnicodeEncodeError: 'ascii'

### ISSUE THREAD

**Issue by d4rkd0s** [mattgwwalker/msg-extractor#3]
I can't provide the original message but there is an attached PDF in the email, its a quote for the company I work for. Is there some missing escaping? Is my .msg file not in the right ascii format? Have you seen this issue before?

Codec can't encode character u'\u2019' in position 4536: ordinal not in range(128)

``` python
Error with file '/Users/myself/Desktop/quote.msg': Traceback (most recent call last):
  File "ExtractMsg.py", line 497, in <module>
    msg.save()
  File "ExtractMsg.py", line 402, in save
    f.write(self.body)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4536: ordinal not in range(128)
```

**Comment by mattgwwalker** [comment]
Hi Logan,

It's pretty impossible to fix any issues without being able to reproduce
them.  If you could find something that produces the same problem but with
something you can share, that would be a great start.

I have however (thanks to your email!) finally got around to accepting
someone's work patching the code so that it works with Python 3.  To be
honest I haven't tried out their work, but at least now it's in the
repository and I hope to test it out myself sometime soon.  But If you'd
like to try it, I think this link should work for you:
https://github.com/mattgwwalker/msg-extractor/archive/master.zip

You might find their changes magically also happen to fix the problem
you've encountered.

I hope that helps! ... And if it does, please keep me informed.

Matthew

**Comment by lordsutch** [comment]
I see the same issue with decoding a message using Python 2.7.10 but not with Python 3.4.3, suggesting that it's a problem with the default encoding in the Python 2 series.

My guess is that using f.write(self.body.encode('utf-8')) instead would fix the problem.

**Comment by joelkaufman** [comment]
from my understanding, this problem occurs when writing the email body, since the email body is UTF-7, it has to be converted to UTF-8, 

    from imapclient import  imapclient
    self.body = imapclient.decode_utf7(self.body)

**Comment by mattgwwalker** [comment]
http://www.gresham.ac.uk/lectures-and-events/a-very-brief-history-of-computing-1948-2015

**Comment by tomrade** [comment]
Just came here after doing a similar patch myself for some emails we had with unusual characters, would be a good balance to maybe add a parameter like --encodeutf, so we have both the "pure" and "not breaks during extract" modes

**Comment by mattgwwalker** [comment]
@tomrade, feel free to add that as a contribution!  I'd be happy to add it in :o)

**Comment by bigme666** [comment]
crude workaround on line 430:
```
else:
                f.write("From: " + xstr(self.sender) + "\n")
                f.write("To: " + xstr(self.to) + "\n")
                f.write("CC: " + xstr(self.cc) + "\n")
                f.write("Subject: " + xstr(self.subject) + "\n")
                f.write("Date: " + xstr(self.date) + "\n")
                f.write("-----------------\n\n")
                bb =  u' '.join(("", self.body)).encode('utf-8').strip()
                f.write(bb)
```

**Comment by claudia-beas** [comment]
In python3 the error can be fixed by using `str(self.body)` since seemingly `str()` is now automatically unicode. `encode()` or `decode()` didn't work for me.

**Comment by d4rkd0s** [comment]
Closing this issue as I am no longer having the issue with the latest code on master.
