### ISSUE TITLE
Error When Extracting/Saving .msg (OLE) Attachment

### ISSUE THREAD

**Issue by fligi7** [mattgwwalker/msg-extractor#31]
It appears msg-extractor is failing when attempting to save a .msg attachment. 

> Error with file 'phishing.msg': Traceback (most recent call last):
  File "ExtractMsg.py", line 543, in <module>
    msg.save(toJson, useFileName)
  File "ExtractMsg.py", line 413, in save
    attachmentNames.append(attachment.save())
  File "ExtractMsg.py", line 193, in save
    f.write(self.data)
TypeError: argument 1 must be string or buffer, not None

**Comment by TheElementalOfCreation** [comment]
Do you mean the attatchment itself is a .msg file? That is a known issue. It has to do with the fact that a .msg attachment is saved as a container in the file, rather than a stream. Because of this, it cannot be retrieved in the same way. Research into how to properly retrieve .msg attachments is currently being made.

If you simply meant the attachment of the .msg file, please post an example file where this is happening.

**Comment by fligi7** [comment]
Yes, was referring to the ability to extract a .msg attachment. Been scouring the internet for a solution but yet to find a way to do this using Python/olefile library. 

Though, I have found a [PowerShell-based method](https://chris.dziemborowicz.com/blog/2013/05/18/how-to-batch-extract-attachments-from-msg-files-using-powershell/) that relies on being run from a Windows system with Outlook installed.

**Comment by fligi7** [comment]
Awesome. Thanks for all the work!

**Comment by TheElementalOfCreation** [comment]
Because I'm using this as a part of a much larger program, I NEEDED to have some of these things done, so its no problem. Besides, I learned a lot more about python while doing it.

**Comment by TheElementalOfCreation** [comment]
Fixed in most recent update. If you believe the issue still exists, please re-open this thread.
