### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ameyn21** [mattgwwalker/msg-extractor#85]
My following code throws an error when removing files from a directory,

`msg = extract_msg.Message(filepath)
msg_sender = msg.sender
msg_to = msg.to

lstFrom = re.findall(r'<([^"]*)>', msg_sender) 
if(lstFrom[0] == DataSubjectEmail):
        shutil.copy(filepath, FromDestination)
        os.remove(filepath)`

**Comment by TheElementalOfCreation** [comment]
Please fill out the issue template we have provided.

**Comment by TheElementalOfCreation** [comment]
Also, that code is very likely to end up failing so find matches due to msg files often dropping the sender email if the sender is the one one to create the msg file. It's really stupid, but I figured you should know.

**Comment by malinowy777** [comment]
Having the same issue ;(

`import os
from os import walk
import re
import extract_msg

f=[]
d=''
s=''
p = r'C:\Users\marcin\Desktop\python_tst'
start_text = "%20%5B"
end_text = "%5D>"

for (p, dirnames, filenames) in walk(p):
    f.extend(filenames)
    break

for i in range(len(f)):
    s=p+'\\'+f[i]
    d=p+'\\folder1\\'+f[i]
    msg = extract_msg.Message(s)
    msg_message = msg.body
    p_id = msg_message[msg_message.find(start_text)+len(start_text):msg_message.find(end_text)]
    os.rename(s,d)`

Error:
`---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-60-929984a1d663> in <module>
     28 # s = r'C:\Users\marcin.malinowski\Desktop\python_tst\plik.docx'
     29 # d = r'C:\Users\marcin.malinowski\Desktop\python_tst\folder1\plik.docx'
---> 30     os.rename(s,d)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\marcin\\Desktop\\python_tst\\_External_ New Comment on _Treasury Functionality_ in Idea Lab – Financials (7).msg' -> 'C:\\Users\\marcin.malinowski\\Desktop\\python_tst\\folder1\\_External_ New Comment on _Treasury Functionality_ in Idea Lab – Financials (7).msg'
`
Has this been been accepted as a bug to be fixed in future release?

**Comment by TheElementalOfCreation** [comment]
@malinowy777 The error is happening in _your_ code. My best guess on your problem is that "folder 1" either doesn't exist (a weird error for that situation, I know) or you don't have permission to write to it. That, or the file is still open and you can't rename it because of that.

Actually, now that I think of it, that is likely your issue too, @ameyn21 .

Both of you should add the line 
```msg.close()```
Before your os/shutil calls.

Remember, the Message class uses an open file to work, so you need to close it to modify the file in many cases.

**Comment by malinowy777** [comment]
@TheElementalOfCreation , I did couple of tests and without 

```
msg = extract_msg.Message(s)
msg_message = msg.body
```

os.rename(s,d) is working as expected.

Will try with msg.close()

**Comment by malinowy777** [comment]
Hey, 
In my case the issue was due to existing file in the destination folder. 
Using `from shutil import move` instead of `from os import walk` resolved the issue

**Comment by Trahan2332** [comment]
Hello,

FYI
My code was raising the same PermissionError when trying to move a file to another folder. It was fixed by closing the file with `msg.close()` as suggested. 

I used the pathlib module to move the file in question via `Path.replace(<targetpath>)`

Code:

`msg = extract_msg.Message(filename)`
`att = msg.attachments`
**Check if att exists**
`if len(att) == 0:` 
`  print(f'No attachments for file: {filename.name}')`
**Check if file exists in target folder**
`  if not output_failure_folder_path.joinpath(filename.name).exists():` 
**If it does not exist**
`    msg.close()`
`    abs_path.replace(output_failure_folder_path.joinpath(filename.name))`
.
.
.

Hope this helps!

**Comment by TheElementalOfCreation** [comment]
This issue seems to have been resolved. Please contact us if it is not.
